### ISSUE TITLE
/validate JSON-LD response structure differs between valid and invalid

### ISSUE THREAD

**Issue by serge-gaia** [surroundaustralia/bdr-public-issues#3]
Here is an example of response for valid data (omitting context for clarity)  
```json
{
  "@context": { },
  "@id": "_:N726b49bd01b14d58bd280cea17504d31",
  "@type": "sh:ValidationReport",
  "sh:conforms": true
}
```
Note that the `"sh:conforms":true` is at the top level

Example of invalid data (also simplified for clarity):
```json
{
  "@context": { },
  "@graph": [
    {
      "@id": "_:Nb6a279f652dd43ef94fdccc80459d7cf",
      "@type": "sh:ValidationReport",
      "sh:conforms": false,
      "sh:result": [
        {
          "@id": "_:N68dd3816685847f3a523bb65dc188657"
        },
        {
          "@id": "_:Nec2f11f63db94769894273bc09b4207e"
        },
        {
          "@id": "_:Na5af282a1b2444b0b22969af4d61bf02"
        },
        {
          "@id": "_:Nb61fb3b6934748e79dcd9d7a72477cd7"
        },
        {
          "@id": "_:N3df52da4bd334e08a1a3513127305dec"
        }
      ]
    }
  ]
}
```
Note that now what was at the top level (e.g `"sh:conforms": false`) is now within the `"@graph"` field.

Not an issue per say but I want to be sure that it is intentional and will stay like that.

**Comment by nicholascar** [comment]
The two forms are isomorphic - you can convert from one to the other and back without loss - but I agree it's not ideal that they both appear. I'll try and ensure that an `@graph` object is always present. I might have to insert some junk into the valid outputs to force it, perhaps some thing like:

```json
{
  "@context": { },
  "@graph": [
     {
      "@id": "_:N726b49bd01b14d58bd280cea17504d31",
      "@type": "sh:ValidationReport",
      "sh:conforms": true,
      "sh:result": []
    }
}
```
where there is an empty array for the `sh:result`. 

Please leave this ticket open for a bit and I'll see if I can get that working shortly. (day or two).

**Comment by serge-gaia** [comment]
If it's not too much trouble but frankly we can deal with both forms.

**Comment by nicholascar** [comment]
OK, I've done as expected above and added a junk `sh:result` value to valid results, so now valid results will also have the `@graph` key in the JSON data like invalid results and look like this:

```json
{
  "@context": {},
  "@graph": [
    {
      "@id": "_:Nc1b19ae71a964ed1af816835b37f3178",
      "@type": "sh:ValidationReport",
      "sh:conforms": true,
      "sh:result": {
        "@id": "_:Ne3a017c548504d2f8747cd88fe782ce9"
      }
    },
    {
      "@id": "_:Ne3a017c548504d2f8747cd88fe782ce9",
      "rdfs:comment": "valid"
    }
  ]
}
```

Let me know how it looks and, if ok, we can close.

**Comment by nicholascar** [comment]
Actually, I'm going to make another update here that will solve Issue #2 too, so just give me a little more time before proper testing.

**Comment by nicholascar** [comment]
OK, I think #2 is solved also.
