### ISSUE TITLE
BDR Gateway `/validate` UI Incorrect Results

### ISSUE THREAD

**Issue by HaydenGaia** [surroundaustralia/bdr-public-issues#4]
## Description
* The BDR Gateway `/validate` endpoint testing user inferface at: http://bdrgateway.surroundaustralia.com/validate appears to validate malformed or invalid data that returns `4XX` status codes.

## Example
![Screenshot from 2022-02-14 15-21-50](https://user-images.githubusercontent.com/99162803/153817989-496e9b63-3c3a-48aa-b854-c7791b53f721.png)

## Expected Result
* Invalid data shows an unsuccessful response, like the `swagger` ui

**Comment by nicholascar** [comment]
I think this is fixed now, try putting in some bad values again!

It was related to the `@graph` issue under the hood...

**Comment by HaydenGaia** [comment]
Seems to work as expected now, thanks!
