### ISSUE TITLE
API gateway timeout at `/validate` and `/absorb` with large dataset

### ISSUE THREAD

**Issue by HaydenGaia** [surroundaustralia/bdr-public-issues#8]
## Description
* Flagging this now, so issues with validation / absorption of "large" datasets can be brought onto the radar
* There will need to be a strategy for how we are going to work with non-trivial size datasets
* Attempting to `/validate` or `/absorb` a "large" dataset (`4.2MB`, ~70,000 lines `ttl`) causes the API gateway to timeout
  * This occurs on the BDR Part-B: http://gateway.dev.bdr.gov.au
  * This also occurs when validating with SURROUND's rdftools: http://http://rdftools.surroundaustralia.com/validate
* Example `rdf`: 
  * [example.zip](https://github.com/surroundaustralia/bdr-public-issues/files/8347193/example.zip)
* Example responses:
  * BDR Part-B:
  * ![1](https://user-images.githubusercontent.com/99162803/160051567-33351a63-5758-465c-9cf2-3886d5a6bba4.png)
  * SURROUND Rdftools:
  * ![2](https://user-images.githubusercontent.com/99162803/160051609-246e0b00-25f2-4d20-be48-b825d8fcd1fc.png)

**Comment by nicholascar** [comment]
OK, thanks @HaydenGaia. Likely we have an internal API default size limit here that we will shift upwards to match the AWS limits.

**Comment by nicholascar** [comment]
Closing since we've at least closed in on what sizes are acceptable.
